@startuml Matheus
    entity "TB_MEDIA_TYPES" as mediaTypes {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_GENRES" as genres {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_PLAYLISTS" as playlists {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_PLAYLIST_TRACK" as playlistTrack {
        PlaylistId: INTEGER <<FK>>
        TrackId: INTEGER <<FK>>
    }

    entity "TB_TRACKS" as tracks {
        *id: INTEGER
        Name: NVARCHAR(200)
        AlbumId: INTEGER <<FK>>
        MediaTypeId: INTEGER <<FK>>
        GenreId: INTEGER <<FK>>
        Composer: NVARCHAR(220)
        Milliseconds: INTEGER
        Bytes: INTEGER
        UnitPrice: NUMERIC
    }

    entity "TB_ARTISTS" as artists {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_ALBUMS" as albums {
        *id: INTEGER
        Name: NVARCHAR(120)
        ArtistId: INTEGER <<FK>>
    }

    entity "TB_INVOICES" as invoices {
        *id: INTEGER
        CustomerId: INTEGER <<FK>>
        InvoiceDate: DATETIME
        BillingAddress: NVARCHAR(120)
        BillingCity: NVARCHAR(120)
    }

    entity "TB_INVOICE_ITEMS" as invoiceItems {
        *id: INTEGER
        Name: NVARCHAR(120)
        InvoiceId: INTEGER <<FK>>
        TrackId: INTEGER <<FK>>
        UnitPrice: NUMERIC
        Quantity: INTEGER
    }

    entity "TB_CUSTOMERS" as customers {
        *id: INTEGER
        FirstName: NVARCHAR(40)
        LastName: NVARCHAR(20)
        Company: NVARCHAR(80)
        Address: NVARCHAR(70)
        City: NVARCHAR(40)
        State: NVARCHAR(40)
        Country: NVARCHAR(40)
        PostalCode: NVARCHAR(10)
        Phone: NVARCHAR(24)
        Fax: NVARCHAR(24)
        Email: NVARCHAR(60)
        SupportRepId: INTEGER <<FK>>
    }

    entity "TB_EMPLOYEES" as employees {
        *id: INTEGER
        FirstName: NVARCHAR(40)
        LastName: NVARCHAR(20)
        Title: NVARCHAR(30)
        ReportsTo: INTEGER
        BirthDate: DATETIME
        HireDate: DATETIME
        Address: NVARCHAR(70)
    }

    mediaTypes ||--o{ tracks
    tracks }o..o| genres
    playlistTrack |o--|| playlists
    playlistTrack |o--|| tracks
    invoiceItems |o--|| tracks
    tracks }o..o| albums
    artists ||--o{ albums
    customers ||--o{ invoices
    customers }o..o| employees
    employees }o..o| employees
@enduml